# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish erdpy docs on Github Pages

on:
  workflow_dispatch:
    inputs:
      ElrondSdkRef:
        description: "Branch (ref) of elrond-sdk"
        required: true
        default: "master"

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout elrond-sdk-docs
      uses: actions/checkout@v2
      with:
        path: elrond-sdk-docs

    - name: Checkout elrond-sdk
      uses: actions/checkout@v2
      with:
        repository: ElrondNetwork/elrond-sdk
        path: elrond-sdk
        ref: ${{ github.event.inputs.elrondSdkRef }}

    - name: Install dependencies for erdpy
      run: |
        sudo apt-get install python3-sphinx
        cd ${GITHUB_WORKSPACE}/elrond-sdk
        pip3 install -r requirements.txt

    - name: Build docs (erdpy)
      run: |
        cd ${GITHUB_WORKSPACE}/elrond-sdk-docs/erdpy
        rm -rf ./source/erdpy.*.rst
        sphinx-apidoc -o ${GITHUB_WORKSPACE}/elrond-sdk-docs/erdpy/source ${GITHUB_WORKSPACE}/elrond-sdk/erdpy
        make html

    - name: Commit and push elrond-sdk-docs
      run: |
        cd ${GITHUB_WORKSPACE}/elrond-sdk-docs
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git commit -m "Update erdpy"
        git push origin
