# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish erdjs docs on Github Pages

on:
  workflow_dispatch:
    inputs:
      ElrondSdkRef:
        description: "Branch (ref) of elrond-sdk"
        required: true
        default: "master"

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout elrond-sdk-docs
      uses: actions/checkout@v2
      with:
        path: elrond-sdk-docs

    - name: Checkout elrond-sdk
      uses: actions/checkout@v2
      with:
        repository: ElrondNetwork/elrond-sdk
        path: elrond-sdk
        ref: ${{ github.event.inputs.elrondSdkRef }}

    - name: Setup NodeJS (for erdjs docs)
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Build docs (erdjs)
      run: |
        cd ${GITHUB_WORKSPACE}/elrond-sdk-docs
        rm -rf ./erdjs
        cd ${GITHUB_WORKSPACE}/elrond-sdk/erdjs
        npm ci
        VERSION=$(node -p "require('./package.json').version")
        npx typedoc --includeVersion --out "${GITHUB_WORKSPACE}/elrond-sdk-docs/erdjs/latest"
        npx typedoc --includeVersion --out "${GITHUB_WORKSPACE}/elrond-sdk-docs/erdjs/${VERSION}"
  
    - name: Commit and push elrond-sdk-docs
      run: |
        cd ${GITHUB_WORKSPACE}/elrond-sdk-docs
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git commit -m "Update erdjs"
        git push origin
